export enum RdfSources {
  ID = "ID",
  TITLE = "TITLE",
  SOURCE = "SOURCE",
  CREATOR = "CREATOR",
  CREATED_DATE = "CREATED_DATE",
  DESCRIPTION = "DESCRIPTION",
  URL = "URL",
  CONTENT_STRUCTURE = "CONTENT_STRUCTURE",
  COVERED_TOPIC = "COVERED_TOPIC",
}
