service: web-dev-companion-be
frameworkVersion: '3'

provider:
  name: aws
  runtime: java17
  environment:
    RDS_ENDPOINT: FakeEndpointChangeIt
    RDS_PORT: FakePortChangeIt
    RDS_DB_NAME: FakeDbNameChangeIt
    RDS_DB_SCHEMA_NAME: FakeDbSchemaNameChangeIt
    RDS_USER: FakeUserChangeIt
    RDS_PWD: FakePwdChangeIt
  stage: dev
  region: eu-west-1
  logRetentionInDays: 1
  apiGateway:
    apiKeys:
      -  web-dev-companion-api-key
    usagePlan:
      limit: 5000
      offset: 2
      period: week
    throttle:
      burstLimit: 10
      rateLimit: 5

# you can add statements to the Lambda function's IAM Role here
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:+
#            - "s3:ListBucket"
#          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#        - Effect: "Allow"
#          Action:
#            - "s3:PutObject"
#          Resource:
#            Fn::Join:
#              - ""
#              - - "arn:aws:s3:::"
#                - "Ref" : "ServerlessDeploymentBucket"
#                - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  artifact: target/${self:service}-${self:provider.stage}.jar

functions:
  UserFilterPreferences:
    handler: com.wed.serverless.UserFilterPreferencesHandler
    events:
      - http:
          path: /api/v1/wed/users/{userId}/preferences
          method: get
          private: true
      - http:
          path: /api/v1/wed/users/{userId}/preferences
          method: delete
          private: true
      - http:
          path: /api/v1/wed/users/{userId}/preferences
          method: post
          private: true
      - http:
          path: /api/v1/wed/users/{userId}/preferences
          method: put
          private: true


#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
